### ISSUE TITLE
Explicitly include base profile?

### ISSUE THREAD

**Issue by beddari** [Mylezeem/puppeels#5]
I see there is inconsistency between the openstack profiles and the rest. In the openstack profiles, the base profile isn't explicitly included.

I'd vote for removing the explicit "include profile::base" in each profile and leave that to the ENC/role/node definition process.

**Comment by Spredzy** [comment]
@beddari `include profile::base` not being included in the openstack profile is a mistake it should be in.

The purpose of `profile::base` is to include everything we want on every single node (ie. `autchonfig`, `ntp`, `sudo`, etc...).

Why not leaving that for ENC as suggested? So people don't have to worry about including it themselves and the class being included automatically.

**Comment by beddari** [comment]
Ok, we got a difference of opinion then.

I think explicitly decoupling as much as possible in the profile layer is the best approach. Then, when you define you role layer, you could write role classes that included base and profiles x-y-z, and still have the possibility of excluding base, e.g use some other implementation of it ....

**Comment by michaeltchapman** [comment]
I've been removing base from everywhere as well. I much prefer to be explicit about which profiles are going on the nodes - profiles should only include other profiles where there is an actual dependency imo - it gets difficult to track otherwise.

On the other hand, ::base can be configured to do absolutely nothing so it's relatively safe.

**Comment by Spredzy** [comment]
@michaeltchapman on a later discussion with @beddari  on IRC, we agreed that `::base` should be optionnal since every user will have diffent needs for a a base class.

**Comment by michaeltchapman** [comment]
@Spredzy @beddari I added this a little while ago https://github.com/michaeltchapman/puppeels/blob/master/manifests/base/base.pp#L23

So you can configure base to do nothing but include a different class.

**Comment by beddari** [comment]
@michaeltchapman I'm all for options but requring including or configuration of base to be able to use/plug one of the application profiles we possibly will maintain is not going to do us any good.

I think removing the explicit includes of profile::base (see #4) and keeping your param for even more flexiblity is the best approach.
